# Generated by Django 4.1 on 2024-03-17 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluentify', '0002_course_reviews_delete_teacher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='Students',
            field=models.IntegerField(auto_created=True, default=0, max_length=10),
        ),
    ]
