# Generated by Django 4.1 on 2024-03-17 20:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluentify', '0003_alter_course_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='Class_Date',
            field=models.CharField(auto_created=True, default=datetime.date(2024, 3, 18), max_length=255),
        ),
        migrations.AlterField(
            model_name='course',
            name='Students',
            field=models.IntegerField(auto_created=True, default=0),
        ),
    ]
